import streamlit as st
import time
import io
from planner import run_planner
from coder import run_coder
from tester import run_tester

st.set_page_config(page_title="AI Code Generator", page_icon="🤖", layout="wide")

# Sidebar
with st.sidebar:
    st.title("🤖 AI Code Generator")
    st.markdown("---")
    
    st.subheader("📋 Example Specs")
    examples = [
        "Build a calculator with add, subtract, multiply and divide functions",
        "Build a string utility library with reverse string, count vowels, and check palindrome",
        "Build a math utility library with square root, power, and check prime functions",
        "Build a list utility library with functions to find max, min, and average",
    ]
    for example in examples:
        if st.button(example, use_container_width=True):
            st.session_state.spec = example

    st.markdown("---")

    # Pipeline history
    st.subheader("🕓 Pipeline History")
    if "history" not in st.session_state:
        st.session_state.history = []

    if st.session_state.history:
        for i, h in enumerate(reversed(st.session_state.history)):
            with st.expander(f"Run {len(st.session_state.history) - i}: {h['spec'][:30]}..."):
                st.write(f"**Tasks:** {h['total']}")
                st.write(f"**Passed:** {h['passed']} ✅")
                st.write(f"**Failed:** {h['failed']} ❌")
                st.write(f"**Time:** {h['time']}s")
    else:
        st.caption("No runs yet.")

# Main area
st.title("🤖 Multi-Agent Code Generator")
st.markdown("Type a plain English description and the AI will plan, write, and test the code automatically.")

spec = st.text_area(
    "What do you want to build?",
    value=st.session_state.get("spec", ""),
    placeholder="e.g. Build a string utility library with functions to reverse a string and count vowels",
    height=100
)

if st.button("🚀 Generate Code", type="primary"):
    if not spec.strip():
        st.warning("Please enter a description first.")
    else:
        st.divider()
        start_time = time.time()

        # Planner
        with st.spinner("🧠 Planner is breaking down your spec..."):
            tasks = run_planner(spec)

        st.success(f"✅ Planner found {len(tasks)} tasks")

        progress_bar = st.progress(0)
        all_code = f"# Generated by Multi-Agent Code Pipeline\n# Spec: {spec}\n\n"
        passed_count = 0
        failed_count = 0
        total_attempts = 0
        results_summary = []

        for i, task in enumerate(tasks):
            st.divider()
            st.subheader(f"📌 Task {i+1}/{len(tasks)}: `{task['name']}`")
            st.caption(task['description'])

            code = None
            passed = False

            for attempt in range(1, 4):
                total_attempts += 1
                with st.spinner(f"⚙️ Generating and testing code..."):
                    code = run_coder(task)
                    result = run_tester(task, code)

                if result["passed"]:
                    st.code(code, language="python")
                    st.success("✅ Tests passed!")
                    passed = True
                    passed_count += 1
                    all_code += code + "\n\n"
                    break

            if not passed:
                st.error(f"❌ Could not generate passing code after 3 attempts")
                failed_count += 1
                if code:
                    all_code += f"# WARNING: Tests failed for {task['name']}\n" + code + "\n\n"
            results_summary.append({
                "task": task["name"],
                "passed": passed
            })

            progress_bar.progress((i + 1) / len(tasks))

        elapsed = round(time.time() - start_time, 1)

        # Save to history
        st.session_state.history.append({
            "spec": spec,
            "total": len(tasks),
            "passed": passed_count,
            "failed": failed_count,
            "time": elapsed
        })

        # Metrics dashboard
        st.divider()
        st.subheader("📊 Pipeline Summary")
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Total Tasks", len(tasks))
        col2.metric("Passed", passed_count)
        col3.metric("Failed", failed_count)
        col4.metric("Time Elapsed", f"{elapsed}s")

        # Results table
        st.subheader("📋 Results")
        for r in results_summary:
            status = "✅ PASSED" if r["passed"] else "❌ FAILED"
            st.write(f"{status} — `{r['task']}`")

        # Download button
        st.divider()
        st.download_button(
            label="⬇️ Download Generated Code",
            data=all_code,
            file_name="generated_code.py",
            mime="text/plain"
        )

        st.balloons()
        st.success("🎉 Pipeline complete!")